### ISSUE TITLE
java.lang.NoSuchFieldError: INTERNAL

### ISSUE THREAD

**Issue by guptatapan** [jgroups-extras/jgroups-kubernetes#150]
I am trying to use jgroups-kubernetes for auto discovery of Artemis cluster.
Artemis version 2.21.0 started using Jgroups 5.2.0.Final, and using jgroups-kubernetes : 2.0.0.Final throws `java.lang.NoSuchFieldError: INTERNAL`

I see a commit is made in master removing the said field : https://github.com/jgroups-extras/jgroups-kubernetes/commit/201dd2b625aee5427a08272bcef2c2cb4ac73c62

Is there any plan to release a new version soon?

Jgroups : 5.2.0.Final
jgroups-kubernetes : 2.0.0.Final

Stacks trace:

2022-05-16 13:40:44,577 ERROR [org.apache.activemq.artemis.core.server] AMQ224097: Failed to start server: java.lang.NoSuchFieldError: INTERNAL
	at org.jgroups.protocols.kubernetes.KUBE_PING.findMembers(KUBE_PING.java:276) [jgroups-kubernetes-2.0.0.Final.jar:]
	at org.jgroups.protocols.Discovery.callFindMembersInAllDiscoveryProtocols(Discovery.java:389) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.Discovery.findMembers(Discovery.java:238) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.Discovery.down(Discovery.java:416) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.MERGE3.down(MERGE3.java:268) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.FD_SOCK.down(FD_SOCK.java:411) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.FailureDetection.down(FailureDetection.java:159) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.VERIFY_SUSPECT.down(VERIFY_SUSPECT.java:102) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.BARRIER.down(BARRIER.java:138) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:614) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.UNICAST3.down(UNICAST3.java:612) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:325) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.pbcast.ClientGmsImpl.joinInternal(ClientGmsImpl.java:67) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.pbcast.ClientGmsImpl.join(ClientGmsImpl.java:37) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.pbcast.GMS.down(GMS.java:897) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:201) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:201) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.stack.Protocol.down(Protocol.java:283) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.FRAG2.down(FRAG2.java:102) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.pbcast.STATE_TRANSFER.down(STATE_TRANSFER.java:205) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.Locking.down(Locking.java:224) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.protocols.COUNTER.down(COUNTER.java:165) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:923) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.JChannel.down(JChannel.java:608) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.JChannel._connect(JChannel.java:808) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.JChannel.connect(JChannel.java:325) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.jgroups.JChannel.connect(JChannel.java:316) [jgroups-5.2.0.Final.jar:5.2.0.Final]
	at org.apache.activemq.artemis.api.core.jgroups.JChannelWrapper.connect(JChannelWrapper.java:126) [artemis-core-client-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.api.core.JGroupsBroadcastEndpoint.internalOpen(JGroupsBroadcastEndpoint.java:113) [artemis-core-client-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.api.core.JGroupsBroadcastEndpoint.openClient(JGroupsBroadcastEndpoint.java:91) [artemis-core-client-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.cluster.DiscoveryGroup.start(DiscoveryGroup.java:111) [artemis-core-client-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.startDiscovery(ServerLocatorImpl.java:285) [artemis-core-client-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.initialize(ServerLocatorImpl.java:269) [artemis-core-client-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.server.cluster.ClusterController.configAndAdd(ClusterController.java:242) [artemis-server-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.server.cluster.ClusterController.addClusterConnection(ClusterController.java:204) [artemis-server-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.server.cluster.ClusterManager.deployClusterConnection(ClusterManager.java:632) [artemis-server-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.server.cluster.ClusterManager.deploy(ClusterManager.java:247) [artemis-server-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.initialisePart1(ActiveMQServerImpl.java:3164) [artemis-server-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.server.impl.LiveOnlyActivation.run(LiveOnlyActivation.java:68) [artemis-server-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.internalStart(ActiveMQServerImpl.java:663) [artemis-server-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.start(ActiveMQServerImpl.java:571) [artemis-server-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.integration.FileBroker.start(FileBroker.java:64) [artemis-cli-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:127) [artemis-cli-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:160) [artemis-cli-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:108) [artemis-cli-2.21.0.jar:2.21.0]
	at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:135) [artemis-cli-2.21.0.jar:2.21.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [java.base:]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [java.base:]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [java.base:]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) [java.base:]
	at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:134) [artemis-boot.jar:2.21.0]
	at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:50) [artemis-boot.jar:2.21.0]

Thanks,
Tapan

**Comment by guptatapan** [comment]
@rhusar SNAPSHOT version is working fine with Jgroups-5.2.0.Final

**Comment by rhusar** [comment]
@guptatapan Just to update on the release, there are ongoing issues with the release infrastructure (https://repository.jboss.org/nexus/) will update once it's releasable into maven again.

**Comment by rhusar** [comment]
The release is out! https://repository.jboss.org/nexus/content/groups/developer/org/jgroups/kubernetes/jgroups-kubernetes/2.0.1.Final/

**Comment by belaban** [comment]
+1!
