### ISSUE TITLE
java.lang.NoSuchMethodError when running library version 0.9.1 with JGroups 3.x

### ISSUE THREAD

**Issue by nvoskresenskiy** [jgroups-extras/jgroups-kubernetes#18]
The following error is encountered when attempting to use KubePing with library version 0.9.1 and jgroups 3.x (tested on 3.6.12.Final):

SEVERE: JGRP000200: failed sending discovery request
java.lang.NoSuchMethodError: org.jgroups.Message.setSrc(Lorg/jgroups/Address;)Lorg/jgroups/Message;
	at org.jgroups.ping.common.OpenshiftPing.sendMcastDiscoveryRequest(OpenshiftPing.java:197)
	at org.jgroups.protocols.PING.sendDiscoveryRequest(PING.java:62)
	at org.jgroups.protocols.PING.findMembers(PING.java:32)
	at org.jgroups.protocols.Discovery.findMembers(Discovery.java:244)
	at org.jgroups.protocols.Discovery.down(Discovery.java:385)
	at org.jgroups.ping.common.OpenshiftPing.down(OpenshiftPing.java:187)
	at org.jgroups.protocols.MERGE3.down(MERGE3.java:261)
	at org.jgroups.protocols.FD_SOCK.down(FD_SOCK.java:384)
	at org.jgroups.protocols.FD_ALL.down(FD_ALL.java:233)
	at org.jgroups.protocols.VERIFY_SUSPECT.down(VERIFY_SUSPECT.java:92)
	at org.jgroups.protocols.BARRIER.down(BARRIER.java:132)
	at org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:582)
	at org.jgroups.protocols.UNICAST3.down(UNICAST3.java:682)
	at org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:347)
	at org.jgroups.protocols.pbcast.ClientGmsImpl.joinInternal(ClientGmsImpl.java:76)
	at org.jgroups.protocols.pbcast.ClientGmsImpl.join(ClientGmsImpl.java:41)
	at org.jgroups.protocols.pbcast.GMS.down(GMS.java:1079)
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:347)
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:347)
	at org.jgroups.protocols.FRAG2.down(FRAG2.java:136)
	at org.jgroups.protocols.RSVP.down(RSVP.java:153)
	at org.jgroups.protocols.pbcast.STATE_TRANSFER.down(STATE_TRANSFER.java:202)
	at org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:1039)
	at org.jgroups.JChannel.down(JChannel.java:790)
	at org.jgroups.JChannel._connect(JChannel.java:564)
	at org.jgroups.JChannel.connect(JChannel.java:294)
	at org.jgroups.JChannel.connect(JChannel.java:279)
	at com.db.mcc.jgroups.test.Main.main(Main.java:11)

The apparent cause is that the org.jgroups.Message#setSrc method has different signature in JGroups 4.0 which 0.9 is compiled against.

The allowed jgroups versions are specified as [3.6.10.Final,4.0] in the pom, so i would assume 3.x still has to be supported

**Comment by slaskawi** [comment]
Yes, of course. That's a regression. I'll fix and release 0.9.2. Thanks for spotting this!
