### ISSUE TITLE
java.lang.NoSuchFieldError: use_ip_addrs

### ISSUE THREAD

**Issue by nikolicjakov** [jgroups-extras/jgroups-kubernetes#30]
Hi, we are having problems using this jgroups extension since it can not find "use_ip_addrs" in class org.jgroups.protocols.Discovery.

`14:57:37,742 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.jgroups.channel.ee.connector: org.jboss.msc.service.StartException in service jboss.jgroups.channel.ee.connector: java.lang.Exception: connecting to channel "ee" failed
	at org.wildfly.clustering.jgroups.spi.service.ChannelConnectorBuilder.start(ChannelConnectorBuilder.java:96)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: connecting to channel "ee" failed
	at org.jgroups.JChannel._connect(JChannel.java:570)
	at org.jgroups.JChannel.connect(JChannel.java:294)
	at org.jgroups.JChannel.connect(JChannel.java:279)
	at org.wildfly.clustering.jgroups.spi.service.ChannelConnectorBuilder.start(ChannelConnectorBuilder.java:94)
	... 5 more
Caused by: java.lang.NoSuchFieldError: use_ip_addrs
	at org.jgroups.protocols.kubernetes.KUBE_PING.findMembers(KUBE_PING.java:176)
	at org.jgroups.protocols.Discovery.findMembers(Discovery.java:244)
	at org.jgroups.protocols.Discovery.down(Discovery.java:384)
	at org.jgroups.protocols.MERGE3.down(MERGE3.java:254)
	at org.jgroups.protocols.FD_SOCK.down(FD_SOCK.java:371)
	at org.jgroups.protocols.FD.down(FD.java:318)
	at org.jgroups.protocols.VERIFY_SUSPECT.down(VERIFY_SUSPECT.java:92)
	at org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:589)
	at org.jgroups.protocols.UNICAST3.down(UNICAST3.java:669)
	at org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:347)
	at org.jgroups.protocols.pbcast.ClientGmsImpl.joinInternal(ClientGmsImpl.java:76)
	at org.jgroups.protocols.pbcast.ClientGmsImpl.join(ClientGmsImpl.java:41)
	at org.jgroups.protocols.pbcast.GMS.down(GMS.java:1087)
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:353)
	at org.jgroups.protocols.FRAG2.down(FRAG2.java:136)
	at org.jgroups.protocols.FORK.down(FORK.java:101)
	at org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:1038)
	at org.jgroups.JChannel.down(JChannel.java:790)
	at org.jgroups.JChannel._connect(JChannel.java:564)
	... 8 more
14:57:37,753 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "jgroups"),
    ("channel" => "ee")
]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.jgroups.channel.ee.connector" => "org.jboss.msc.service.StartException in service jboss.jgroups.channel.ee.connector: java.lang.Exception: connecting to channel \"ee\" failed
    Caused by: java.lang.Exception: connecting to channel \"ee\" failed
    Caused by: java.lang.NoSuchFieldError: use_ip_addrs"}}`

**Comment by slaskawi** [comment]
Could you please tell me what JGroups/KUBE_PING versions are you using?

**Comment by nikolicjakov** [comment]
JGroups version = 3.6.6 Final
JGroups Kubernetes version = 1.0.0 Beta1

**Comment by slaskawi** [comment]
Unfortunately KUBE_PING `1.0.0.Beta1` can only be used with JGroups 4 (see https://github.com/jgroups-extras/jgroups-kubernetes/blob/master/pom.xml#L56).

**Comment by nikolicjakov** [comment]
Ahh my bad.... sry. But if i update jgroups my keycloak wont start, daamn i am stuck... :(

**Comment by slaskawi** [comment]
Yes, in that case the `stable` releases (`0.9.x`) are for you. They support both JGroups 3 and 4.

Is there something in `0.9.x` that forces you to migrate into `1.x.x`?

**Comment by nikolicjakov** [comment]
No, not rly. I was just greedy wanting latest and greatest. :+1:

**Comment by slaskawi** [comment]
hahah Ok, than :) Closing the ticket.

**Comment by nikolicjakov** [comment]
@slaskawi Can i just quickly ask you something. Now that i am using jgroups 3.6.6 and kubernetes-0.9.3.jar i am still not able to startup keycloak instance due to error.

`09:28:55,423 WARN  [org.jboss.modules] (ServerService Thread Pool -- 15) Failed to define class org.jgroups.ping.kube.KubePing in Module "org.jgroups-kubernetes:main" from local module loader @33e5ccce (finder: local module finder @5a42bbf4 (roots: /opt/jboss/keycloak/modules,/opt/jboss/keycloak/modules/system/layers/keycloak,/opt/jboss/keycloak/modules/system/layers/base)): java.lang.NoClassDefFoundError: Failed to link org/jgroups/ping/kube/KubePing (Module "org.jgroups-kubernetes:main" from local module loader @33e5ccce (finder: local module finder @5a42bbf4 (roots: /opt/jboss/keycloak/modules,/opt/jboss/keycloak/modules/system/layers/keycloak,/opt/jboss/keycloak/modules/system/layers/base))): org/jgroups/ping/common/OpenshiftPing
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [rt.jar:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [rt.jar:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [rt.jar:1.8.0_131]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:446) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.Module.loadModuleClass(Module.java:605) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93) [jboss-modules.jar:1.5.1.Final]
	at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.8.0_131]
	at java.lang.ClassLoader.defineClass(Unknown Source) [rt.jar:1.8.0_131]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:358) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:437) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.Module.loadModuleClass(Module.java:605) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93) [jboss-modules.jar:1.5.1.Final]
	at org.jboss.as.clustering.jgroups.subsystem.ProtocolResourceRegistrationHandler.findProtocolClass(ProtocolResourceRegistrationHandler.java:179) [wildfly-clustering-jgroups-extension-10.0.0.Final.jar:10.0.0.Final]
	at org.jboss.as.clustering.jgroups.subsystem.ProtocolResourceRegistrationHandler.execute(ProtocolResourceRegistrationHandler.java:143) [wildfly-clustering-jgroups-extension-10.0.0.Final.jar:10.0.0.Final]
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890) [wildfly-controller-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659) [wildfly-controller-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370) [wildfly-controller-2.0.10.Final.jar:2.0.10.Final]
	at org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStepHandler.java:359) [wildfly-controller-2.0.10.Final.jar:2.0.10.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [rt.jar:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [rt.jar:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [rt.jar:1.8.0_131]
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)`

**Comment by slaskawi** [comment]
Sorry for late response, I was on PTO.

It seems that your module doesn't contain `org.jgroups.kubernetes:common`. Here's an example how we define it in Infinispan: https://github.com/infinispan/infinispan/blob/9.0.0.Final/server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/jgroups/kubernetes/kubernetes/main/module.xml#L9-L12
