### ISSUE TITLE
Occasional NPE on shutdown

### ISSUE THREAD

**Issue by slaskawi** [jgroups-extras/jgroups-kubernetes#39]
```
11:28:15,820 ERROR [org.jgroups.util.TimeScheduler3] (jgroups-3,a0a320fc356b) JGRP000169: failed executing taskMERGE3: InfoSender: java.lang.NullPointerException
	at org.jgroups.protocols.kubernetes.KUBE_PING.readAll(KUBE_PING.java:244) [jgroups-kubernetes-1.0.0.Beta1-redhat-1.jar:]
	at org.jgroups.protocols.kubernetes.KUBE_PING.findMembers(KUBE_PING.java:171) [jgroups-kubernetes-1.0.0.Beta1-redhat-1.jar:]
	at org.jgroups.protocols.Discovery.findMembers(Discovery.java:206) [jgroups-4.0.4.Final-redhat-1.jar:4.0.4.Final-redhat-1]
	at org.jgroups.protocols.Discovery.down(Discovery.java:348) [jgroups-4.0.4.Final-redhat-1.jar:4.0.4.Final-redhat-1]
	at org.jgroups.protocols.MERGE3$InfoSender.run(MERGE3.java:392) [jgroups-4.0.4.Final-redhat-1.jar:4.0.4.Final-redhat-1]
	at org.jgroups.util.TimeScheduler3$Task.run(TimeScheduler3.java:324) [jgroups-4.0.4.Final-redhat-1.jar:4.0.4.Final-redhat-1]
	at org.jgroups.util.TimeScheduler3$RecurringTask.run(TimeScheduler3.java:358) [jgroups-4.0.4.Final-redhat-1.jar:4.0.4.Final-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_151]

```

**Comment by rhusar** [comment]
Closing for now as this hasn't been reported by QE in the past year. Please reopen @slaskawi if problem can be hit again with updated line numbers.

**Comment by pkremens** [comment]
I saw that one in logs today (JGroups version 4.1.4). I can report an issue in case that I'll see it more often, or it will somehow start to break our tests. The exception popped up during the server shutdown.

```
05:52:55,086 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000080: Disconnecting JGroups channel ee
05:52:55,095 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000080: Disconnecting JGroups channel ee
05:52:55,098 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-1) WFLYMAIL0002: Unbound mail session [java:jboss/mail/Default]
05:52:55,102 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000080: Disconnecting JGroups channel ee
05:52:55,115 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 81) WFLYUT0022: Unregistered web context: '/' from server 'default-server'
05:52:55,132 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0019: Host default-host stopping
05:52:55,130 INFO  [org.jboss.modcluster] (ServerService Thread Pool -- 18) MODCLUSTER000002: Initiating mod_cluster shutdown
05:52:55,183 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-1) WFLYJCA0011: Unbound JCA ConnectionFactory [java:/jbamqa-amq/ConnectionFactory]
05:52:55,184 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-1) WFLYJCA0011: Unbound JCA AdminObject [java:/queue/xaQueue2]
05:52:55,184 INFO  [org.jboss.as.connector.deployment] (MSC service thread 1-1) WFLYJCA0011: Unbound JCA AdminObject [java:/queue/xaQueue1]
05:52:55,230 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 18) WFLYCLINF0003: Stopped client-mappings cache from ejb container
05:52:55,272 INFO  [org.infinispan.remoting.transport.jgroups.JGroupsTransport] (MSC service thread 1-1) ISPN000080: Disconnecting JGroups channel ee
05:52:55,314 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0028: Stopped deployment ROOT.war (runtime-name: ROOT.war) in 296ms
05:52:55,313 ERROR [org.jgroups.util.TimeScheduler3] (thread-6,null,xa-load-2) JGRP000169: failed executing task MERGE3: InfoSender: java.lang.NullPointerException
	at org.jgroups.protocols.kubernetes.KUBE_PING.readAll(KUBE_PING.java:313)
	at org.jgroups.protocols.kubernetes.KUBE_PING.findMembers(KUBE_PING.java:206)
	at org.jgroups.protocols.Discovery.invokeFindMembers(Discovery.java:216)
	at org.jgroups.protocols.Discovery.findMembers(Discovery.java:241)
	at org.jgroups.protocols.Discovery.down(Discovery.java:384)
	at org.jgroups.protocols.MERGE3$InfoSender.run(MERGE3.java:413)
	at org.jgroups.util.TimeScheduler3$Task.run(TimeScheduler3.java:328)
	at org.jgroups.util.TimeScheduler3$RecurringTask.run(TimeScheduler3.java:362)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.jboss.as.clustering.jgroups.ClassLoaderThreadFactory.lambda$newThread$0(ClassLoaderThreadFactory.java:52)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rhusar** [comment]
I see where this is coming from. Its another race on close.

**Comment by rhusar** [comment]
@pkremens Thanks for the update - opened WF tracker as well to keep track of this https://issues.redhat.com/browse/WFLY-13006

**Comment by pkremens** [comment]
Perfect, thanks for an update.
