### ISSUE TITLE
Cluster formation using KUBE_PING

### ISSUE THREAD

**Issue by CalamarBicefalo** [jgroups-extras/jgroups-kubernetes#59]
I believe this is not strictly related to jgroups, but It might help others too:

I am deploying Keycloak in kubernetes, and have been messing around with KUBE_PING for a week now. I get jGroups to form a cluster, but infinispan cannot propagate the initial state, therefore preventing the cluster from becoming healthy.

The cluster uses KUBE_PING
`Setting JGroups discovery to kubernetes.KUBE_PING with properties {port_range=>1}`

The coordinator uses KUBE_PING to form a cluster successfully

```
10:37:50,295 INFO  [org.infinispan.CLUSTER] (thread-9,ejb,keycloak-59c67569f7-wvjmn) ISPN000094: Received new cluster view for channel ejb: [keycloak-59c67569f7-wvjmn|1] (2) [keycloak-59c67569f7-wvjmn, keycloak-59c67569f7-6fdd6]
10:37:50,299 INFO  [org.infinispan.CLUSTER] (thread-9,ejb,keycloak-59c67569f7-wvjmn) ISPN100000: Node keycloak-59c67569f7-6fdd6 joined the cluster
[...]
10:37:52,166 INFO  [org.infinispan.CLUSTER] (remote-thread--p7-t2) [Context=actionTokens] ISPN100002: Starting rebalance with members [keycloak-59c67569f7-wvjmn, keycloak-59c67569f7-6fdd6], phase READ_OLD_WRITE_ALL, topology id 2
[...]
10:37:52,174 INFO  [org.infinispan.CLUSTER] (remote-thread--p7-t8) [Context=work] ISPN100002: Starting rebalance with members [keycloak-59c67569f7-wvjmn, keycloak-59c67569f7-6fdd6], phase READ_OLD_WRITE_ALL, topology id 2
```

The initial cache transfer starts. The coordinator starts getting timeouts:

```
10:38:24,999 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p10-t1) ISPN000136: Error executing command RemoveCommand, writing keys [98c9eca3-80c3-47b6-a3a7-59dc2a7207f1]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 2 from keycloak-59c67569f7-6fdd6
        at org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:167)
        at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
        at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

10:38:35,036 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p10-t1) ISPN000136: Error executing command PutKeyValueCommand, writing keys [98c9eca3-80c3-47b6-a3a7-59dc2a7207f1]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 3 from keycloak-59c67569f7-6fdd6
        at org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:167)
        at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
        at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

On the other hand the other node gets stuck on the state transfer until eventually it gives up:

```
10:37:52,033 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 52) WFLYCLINF0002: Started keys cache from keycloak container
10:37:52,034 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 53) WFLYCLINF0002: Started realms cache from keycloak container
10:37:52,036 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 54) WFLYCLINF0002: Started authorization cache from keycloak container
10:37:52,036 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 61) WFLYCLINF0002: Started users cache from keycloak container
//It stagnates here
```

**Comment by belaban** [comment]
The cluster forms successfully, so this is not a JGroups issue (at least not in the discovery phase). I suggest contact the keycloak/Infinispan folks, to see if this is a problem in their code.

**Comment by rhusar** [comment]
Closing – this is not indicative of problem with KUBE_PING. Please file in the appropriate place.
